twilio: # Twilio gateway configuration
  accountId: AC6b5d059a5df8ac08af904e46b68ed995 #fake
  accountToken: d1ec5b0c74593aaffdcc7bde533a04f2 #fake
  numbers: # Numbers allocated in Twilio
    - # First number
    - # Second number
    - # Third number
    - # ...
    - # Nth number
    - "+12055768747" #fake
  messagingServicesId: 
  localDomain: 192.168.1.168 # Domain Twilio can connect back to for calls. Should be domain of your service.

push:
  queueSize: 200 # Size of push pending queue

redphone:
  authKey: # Deprecated

turn: # TURN server configuration
  secret: 121654fjdfgdyesdfgfhgh # TURN server secret
  uris:
    - stun:yourdomain:80
    - stun:yourdomain.com:443
    - turn:yourdomain:443?transport=udp
    - turn:etc.com:80?transport=udp

cache: # Redis server configuration for cache cluster
  url: "redis://127.0.0.1:6379/1"
  replicaUrls:
    - "redis://redit:6379/2"

directory:
  redis: # Redis server configuration for directory cluster
    url: "redis://redit:6379/0"
    replicaUrls:
      - "redis://redit:6379/4"
  client: # Configuration for interfacing with Contact Discovery Service cluster
    userAuthenticationTokenSharedSecret: test # hex-encoded secret shared with CDS used to generate auth tokens for Signal users
    userAuthenticationTokenUserIdSecret: test# hex-encoded secret shared among Signal-Servers to obscure user phone numbers from CDS
  sqs:
    accessKey: AKIAIOSFODNN7EXAMPLE    # AWS SQS accessKey
    accessSecret: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY  # AWS SQS accessSecret
    queueUrl:  sqs://127.0.0.1    # AWS SQS queue url
  server:
    replicationUrl: http://127.0.0.2               # CDS replication endpoint base url
    replicationPassword:  12321312         # CDS replication endpoint password
    replicationCaCertificate: 5656     # CDS replication endpoint TLS certificate trust root
    reconciliationChunkSize:   12    # CDS reconciliation chunk size
    reconciliationChunkIntervalMs 99999999 : # CDS reconciliation chunk interval, in milliseconds
    
messageCache: # Redis server configuration for message store cache
  url: "redis://127.0.0.1:6379/2"

messageStore: # Postgresql database configuration for message store
  driverClass: org.postgresql.Driver
  user: Signal
  password: Signal!!
  url: "jdbc:postgresql://127.0.0.1:5432/messagedb"

attachments: # AWS S3 configuration
  accessKey: AKIAIOSFODNN7EXAMPLE
  accessSecret: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  bucket: signal

profiles: # AWS S3 configuration
  accessKey: AKIAIOSFODNN7EXAMPLE
  accessSecret: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  bucket: profile
  region: us-east-1

database: # Postgresql database configuration
  driverClass: org.postgresql.Driver
  user: Signal
  password: Signal!!
  url: "jdbc:postgresql://127.0.0.1:5432/accountdb"
  properties:
    charSet: UTF-8

apn: # Apple Push Notifications configuration
  bundleId:
  pushCertificate:
  pushKey:

gcm: # GCM Configuration
  senderId: 412918270132 #fake
  apiKey: AIzaSyC8gPzceq2SPebZZWaD3I9OeqePyD9CUqk #fake
