twilio: # Twilio gateway configuration
  accountId: AC6b5d059a5df8ac08af904e46b68ed995 #fake
  accountToken: d1ec5b0c74593aaffdcc7bde533a04f2 #fake
  numbers:  # Numbers allocated in Twilio
    - "+12055768747" #fake
  messagingServicesId: 
  localDomain: 192.168.1.168 # Domain Twilio can connect back to for calls. Should be domain of your service.

push:
  queueSize: 200 # Size of push pending queue

#redphone:
#  authKey: 12312321 # Deprecated

turn: # TURN server configuration
  secret: 121654fjdfgdyesdfgfhgh # TURN server secret
  uris:
    - stun:yourdomain:80
    - stun:yourdomain.com:443
    - turn:yourdomain:443?transport=udp
    - turn:etc.com:80?transport=udp

cache: # Redis server configuration for cache cluster
  url: "redis://127.0.0.1:6379/1"
  replicaUrls:
    - "redis://redit:6379/2"

directory:
  redis: # Redis server configuration for directory cluster
    url: "redis://redit:6379/3"
    replicaUrls:
      - "redis://redit:6379/4"
  client: # Configuration for interfacing with Contact Discovery Service cluster
    userAuthenticationTokenSharedSecret: test # hex-encoded secret shared with CDS used to generate auth tokens for Signal users
    userAuthenticationTokenUserIdSecret: test# hex-encoded secret shared among Signal-Servers to obscure user phone numbers from CDS
  sqs:
    accessKey: AKIAIOSFODNN7EXAMPLE    # AWS SQS accessKey
    accessSecret: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY  # AWS SQS accessSecret
    queueUrl:  sqs://127.0.0.1    # AWS SQS queue url
  server:
    replicationUrl: http://127.0.0.2               # CDS replication endpoint base url
    replicationPassword:  12321312         # CDS replication endpoint password
    replicationCaCertificate: 5656     # CDS replication endpoint TLS certificate trust root
    
messageCache: # Redis server configuration for message store cache
  redis:
    url: "redis://127.0.0.1:6379/5"
    replicaUrls:
      - "redis://127.0.0.1:6379/6"

messageStore: # Postgresql database configuration for message store
  driverClass: org.postgresql.Driver
  user: Signal
  password: Signal!!
  url: "jdbc:postgresql://127.0.0.1:5432/messagedb"

attachments: # AWS S3 configuration
  accessKey: AKIAIOSFODNN7EXAMPLE
  accessSecret: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  bucket: signal
  region: us-east-1

profiles: # AWS S3 configuration
  accessKey: AKIAIOSFODNN7EXAMPLE
  accessSecret: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  bucket: profile
  region: us-east-1

database: # Postgresql database configuration
  driverClass: org.postgresql.Driver
  user: Signal
  password: Signal!!
  url: "jdbc:postgresql://127.0.0.1:5432/accountdb"
  properties:
    charSet: UTF-8

apn: # Apple Push Notifications configuration
  bundleId: 1312312
  pushCertificate: 31231
  pushKey: 12321321

gcm: # GCM Configuration
  senderId: 412918270132 #fake
  apiKey: AIzaSyC8gPzceq2SPebZZWaD3I9OeqePyD9CUqk #fake

accountDatabaseCrawler:
  chunkSize: 100
  chunkIntervalMs: 8000

recaptcha:
  secret: 666666

pushScheduler:
  url: "redis://localhost:6379/7"
  replicaUrls: 
    - "redis://localhost:6379/8"

unidentifiedDelivery:
  privateKey: "-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-128-CBC,F9B307A12596523AA92357E3949FD460

09PzH4NPCtX84HHhF80ss4RxFfzT8M/xazs5RIHRQyZwneusKtWxSIqU3taxNiIp
rUgYIC0rSnVNGU14PDqSUMBvav39JxncIAw63GNDuBIUovg0bddC6JSYF80c9vJV
0vkG1lAeGQfkaGOXn8GysvuEC62xmKkh7HkCmdVE2yXFy8wf3vvqgmJ5iZcdD/HE
sMzDRu8Ddve57zTiEZhYbyA0bdyTO+A4Oo/d0gjqBrWY/P879f00ioLOl0kxKZln
jLLgXR1zY/8cu/MtQR5CXTPFwBOE/FVE3hZduWBf2/DuJUwVnfyqmvkm4hQfbkdE
9hl8NZxD0eTm2jQOZoO//4mJTtrwt2LQJ3ITD2JfmwjlPxewGQI8j6Weq6kgi9tN
Upf8iNki2LuLaYLZICmQQM8uwu9WAzjG/Mq/BKCPcWHce4B/YdnrdZuTseRfdqvV
tk2utXM9KTXu1LU9P4TdSJ12ibqXI8oMA5SnkNhP/Z8OZ142OqQI0hq1hdL0yXyo
YaaYnhEKi+LQNUPqtSijWG/5tpSUuo7sKjbAIT3pRajvWVF2Ewat5RzhgdrIdYKe
0qKEpC0drPgfaJIR3EypiTAgQhESeL1GrWV6uaS/avJBayqS5ROIkEvzKRemFnEY
fI5LqgDkNrPhY49g6yi4tz6+4cUTfxbnB4lhLm2bI1vbeDJ2wkDaD0jTft7tdZf7
oFvyyphQM3D5T63Q6MY3A3JLXuV8A6/KYk7iZzGGON0F5/xZD/du8IvG+9rfgx7V
inJsW9eA5YXIKplOa1ZXgov9p1YKw2BjbU/L0p809lgVwwX+A85eO6ZBdDFc2xXi
gwuLlMn1/cKcYF8QrcPPyFvG8Oy8ok133pEWt3ednitUcKZiuj9PP2ECE7+o2GTp
OSSDrEir4dgHmD46MK3HE3/OFLdK/gZXyDO46/eJ+7JFrUNW/pm38bCo4BABWumm
e5IhYDOe5pH/HqVGJBsBNS0nP7MGbPDBBbwSInCRqBu5RabO+Ty40y5DE25KvQnS
8ngl1mVte9nIv9cGgEzw3NbHXFY7GVpbgSbCAnfcw95T+KNmieccRY5UpP2op6s4
dixPrrj136cIDPzVtx8m87xF+uCYRErGv3yWsNaWuODnb1UASjzDRU54kEDE1u/f
Fd3C3vYTGfONwpu/owblygt2T4K00byafV47/qx1mxXVVNHhavkLDfUavsrqnLOn
wMRQL4Evof0zlST/OL/wA6pNdd26Livnl+6E9wlOZ/9Rpi9J8KPJ3xJL3UUraDB4
nQoPAqywaV3WDauZc3GvNTpxi5fXviBrz+xmtpoJkQrb8LDAcKGY5wHja2AutEzj
8ZRkqu2GFa52hk7qdvy/LYKTqKgOulcIpPoa3FtY5JqRhLsPCYBwsgeD/E37gaVO
VqsEhhIcsUWsH3UDo/YC3POa4cn0TVolcypnyRVCSshLhJkmQHJ5eEhRjRTisBtn
tRU37LCYwbCPApsFLm8ppNr47z0gsJKINFTM0YrnIsfmGVadZEP648l9rSmf1hhH
0NQz22trSTLMCRtdgeijgm248uWDRRPEB3CzYrInaDO+cnGEsLV1qCVjXqh7uBPA
-----END RSA PRIVATE KEY-----"
  certificate: "-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyengTimTzVEYLKCQ4qE1
z1ME5MKVAMebj5/DkuwdPMuQHu1dUZoRQxDU1f8VUdrElfLXGTYUjHh4e4erpMxr
CI7sHyn6ov8Gw+njOvN8IdgH7QlT8xyHeCKsxBl/WaUTy+lGU7CgrDdM+ZOiQODF
F0JFx1yOU80Qln5FO5yFEw+DVeUnXgWMDpjoUTXC1GUICaGLaT64X1qgPykyjAbI
kEUCw7PNV8RxIgWCd0JSEZmRlVhhfeSsgWCX6UFZubs/cATqsrXkQbLjHvEN0eNC
+vzOWIlNEhRdn5cwPOpz9nxneMrMSxl1UvDf88ze2IFvE6V+82a0P0XcjtSRDd6V
owIDAQAB
-----END PUBLIC KEY-----"
  expiresDays: 3650

voiceVerification:
  url: http://localhost
  locales:
    - zh